message(STATUS "Configuring STM32 toolchain")

set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(TOOLCHAIN_PREFIX arm-none-eabi CACHE STRING
  "GNU Arm Embedded toolchain executable prefix"
)
set(MCPU cortex-m33 CACHE STRING
  "Arm CPU passed to the STM32 compiler and linker"
)
set(MFPU fpv5-sp-d16 CACHE STRING
  "Arm FPU passed to the STM32 compiler and linker"
)
set(MFLOAT_ABI hard CACHE STRING
  "Arm floating point ABI passed to the STM32 compiler and linker"
)

find_program(STM32_C_COMPILER NAMES ${TOOLCHAIN_PREFIX}-gcc REQUIRED)
find_program(STM32_CXX_COMPILER NAMES ${TOOLCHAIN_PREFIX}-g++ REQUIRED)
find_program(STM32_ASM_COMPILER NAMES ${TOOLCHAIN_PREFIX}-gcc REQUIRED)
find_program(STM32_OBJCOPY NAMES ${TOOLCHAIN_PREFIX}-objcopy REQUIRED)
find_program(STM32_SIZE NAMES ${TOOLCHAIN_PREFIX}-size REQUIRED)

set(CMAKE_C_COMPILER   "${STM32_C_COMPILER}" CACHE FILEPATH "" FORCE)
set(CMAKE_CXX_COMPILER "${STM32_CXX_COMPILER}" CACHE FILEPATH "" FORCE)
set(CMAKE_ASM_COMPILER "${STM32_ASM_COMPILER}" CACHE FILEPATH "" FORCE)
set(CMAKE_OBJCOPY      "${STM32_OBJCOPY}" CACHE FILEPATH "" FORCE)
set(CMAKE_SIZE         "${STM32_SIZE}" CACHE FILEPATH "" FORCE)
set(CMAKE_EXECUTABLE_SUFFIX ".elf")
set(CMAKE_EXECUTABLE_SUFFIX_C ".elf")
set(CMAKE_EXECUTABLE_SUFFIX_CXX ".elf")
set(CMAKE_EXECUTABLE_SUFFIX_ASM ".elf")

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
